<?php

namespace Database\Factories;

use App\Models\Project;
use App\Models\Ticket;
use App\Models\TicketPriority;
use App\Models\TicketStatus;
use App\Models\TicketType;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Ticket>
 *
 * Note: `code` and `order` are generated by the Ticket model's creating hook,
 * so they are deliberately omitted here.
 */
class TicketFactory extends Factory
{
    protected $model = Ticket::class;

    public function definition(): array
    {
        return [
            'name' => fake()->sentence(4),
            'content' => fake()->paragraph(),
            'owner_id' => User::factory(),
            'responsible_id' => null,
            'status_id' => TicketStatus::factory(),
            'project_id' => Project::factory(),
            'type_id' => TicketType::factory(),
            'priority_id' => TicketPriority::factory(),
            'estimation' => null,
            'epic_id' => null,
            'sprint_id' => null,
        ];
    }

    public function estimated(float $hours): static
    {
        return $this->state(fn () => ['estimation' => $hours]);
    }
}
